<a href="https://colab.research.google.com/github/lakshmant-thota/ml_zoomcamp/blob/master/numpy_practice.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np

## NumPy arrays

Creating arrays

* `np.zeros`
* `np.ones`
* `np.full`
* `np.repeat`
* `np.array`
* `np.arange`

In [ ]:
zeros = np.zeros(10)
zeros

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [ ]:
ones = np.ones(10)
ones

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [ ]:
z = np.zeros_like(ones)
z

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [ ]:
array = np.full(10, 0.0)
array

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [ ]:
array = np.repeat(0.0, 10)
array

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [ ]:
array = np.repeat([0.0, 1.0], 5)
array

array([0., 0., 0., 0., 0., 1., 1., 1., 1., 1.])

In [ ]:
array = np.repeat([0.0, 1.0], [2, 3])
array

array([0., 0., 1., 1., 1.])

Accessing the element of an array by index:

In [ ]:
el = array[1]
print(el)

0.0


Accessing multuple elements of an array by a list of indices:

In [ ]:
array[[4, 2, 0]]

array([1., 1., 0.])

Assignment:

In [ ]:
array[1] = 1
print(array)

[0. 1. 1. 1. 1.]


Creating an array from a list with integers:

In [ ]:
elements = [1, 2, 3, 4]
array = np.array(elements)
array

array([1, 2, 3, 4])

Specifying the type of elements:

In [ ]:
zeros = np.zeros(10, dtype=np.uint8)
zeros

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0], dtype=uint8)

`np.arange` for creating ranges:

In [ ]:
for i in np.arange(5):
    print(i)

0
1
2
3
4


Linspace - for creating an array with elements from `start` till `end` of a certain size:

In [ ]:
thresholds = np.linspace(0, 1, 11)
thresholds

array([0. , 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 1. ])

Be careful with overflowing:

In [ ]:
zeros[0] = 300
zeros

array([44,  0,  0,  0,  0,  0,  0,  0,  0,  0], dtype=uint8)

In [ ]:
zeros[0] = 300
print(zeros[0])

300.0


In [ ]:
300 % 256

44

## Multi-dimensional NumPy arrays

Specify the shape with a tuple:

In [ ]:
zeros = np.zeros((5, 2), dtype=np.float32)
zeros

array([[0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.]], dtype=float32)

In [ ]:
print(zeros.shape)

(5, 2)


In [ ]:
numbers = [
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
]

numbers = np.array(numbers)

In [ ]:
print(numbers[0, 1])

2


Assignment: use a tuple (row index, column index)

In [ ]:
numbers[0, 1] = 10

In [ ]:
numbers

array([[ 1, 10,  3],
       [ 4,  5,  6],
       [ 7,  8,  9]])

In [ ]:
numbers[0]

array([ 1, 10,  3])

Slicing: getting a column:

In [ ]:
numbers[2,:]

array([7, 8, 9])

In [ ]:
numbers[:, 1]

array([10,  5,  8])

Assigning a row:

In [ ]:
numbers[1] = [1, 1, 1]

In [ ]:
numbers

array([[ 1, 10,  3],
       [ 1,  1,  1],
       [ 7,  8,  9]])

Assigning a column:

In [ ]:
numbers[:, 2] = [9, 9, 9]

In [ ]:
numbers

array([[ 1, 10,  9],
       [ 1,  1,  9],
       [ 7,  8,  9]])

In [ ]:
np.random.seed(2)



In [ ]:
np.random.seed(10)
np.random.randint(low=0, high=10, size=(5, 2))





array([[9, 4],
       [0, 1],
       [9, 0],
       [1, 8],
       [9, 0]])

## Randomly generated arrays


Uniform random numbers between 0 and 1 of shape (5, 2):

In [ ]:
np.random.rand(5, 2)

array([[0.28875881, 0.35140886],
       [0.58407046, 0.43713904],
       [0.05416264, 0.29666846],
       [0.98028613, 0.08803755],
       [0.14793322, 0.27545387]])

Set seed for reproducibility:

In [ ]:
np.random.seed(2)
arr = np.random.rand(5, 2)
arr

array([[0.4359949 , 0.02592623],
       [0.54966248, 0.43532239],
       [0.4203678 , 0.33033482],
       [0.20464863, 0.61927097],
       [0.29965467, 0.26682728]])

In [ ]:
np.random.seed(2)
np.random.randn(5, 2)

array([[-0.41675785, -0.05626683],
       [-2.1361961 ,  1.64027081],
       [-1.79343559, -0.84174737],
       [ 0.50288142, -1.24528809],
       [-1.05795222, -0.90900761]])

Random integers between 0 and 99 (100 is not included)

In [ ]:
np.random.seed(2)
np.random.randint(low=0, high=100, size=(5, 2))

array([[40, 15],
       [72, 22],
       [43, 82],
       [75,  7],
       [34, 49]])

## Element-wise operations

In [ ]:
rng = np.arange(5)
rng

array([0, 1, 2, 3, 4])

Every item in the array is multiplied by 2:

In [ ]:
rng * 2

array([0, 2, 4, 6, 8])

In [ ]:
(rng - 1) * 3 / 2 + 1

array([-0.5,  1. ,  2.5,  4. ,  5.5])

Adding one array with another

In [ ]:
np.random.seed(2)
noise = 0.01 * np.random.rand(5)
noise

array([0.00435995, 0.00025926, 0.00549662, 0.00435322, 0.00420368])

In [ ]:
numbers = np.arange(5)
numbers

array([0, 1, 2, 3, 4])

In [ ]:
result = numbers + noise
result

array([0.00435995, 1.00025926, 2.00549662, 3.00435322, 4.00420368])

Rounding the numbers to 4th digit:

In [ ]:
result.round(4)

array([0.0044, 1.0003, 2.0055, 3.0044, 4.0042])

Two ways to square each element:

* element-wise multiplication with itself
* the power operator (`**`)

In [ ]:
np.random.seed(2)
pred = np.random.rand(3).round(2)
pred

array([0.44, 0.03, 0.55])

In [ ]:
square = pred * pred
square

array([0.1936, 0.0009, 0.3025])

In [ ]:
square = pred ** 2
square

array([0.1936, 0.0009, 0.3025])

Other element-wise operations:

- `exp`
- `log`
- `sqrt`

In [ ]:
np.exp(pred)

array([1.55270722, 1.03045453, 1.73325302])

In [ ]:
np.log(pred)

array([-0.82098055, -3.5065579 , -0.597837  ])

In [ ]:
np.sqrt(pred)

array([0.66332496, 0.17320508, 0.74161985])

### Comparison operations

In [ ]:
np.random.seed(2)
pred = np.random.rand(3).round(2)
pred

array([0.44, 0.03, 0.55])

In [ ]:
result = pred >= 0.5
result

array([False, False,  True])

In [ ]:
np.random.seed(2)


In [ ]:
pred1 = np.random.rand(3).round(2)
pred1

array([0.44, 0.03, 0.55])

In [ ]:
pred2 = np.random.rand(3).round(2)
pred2

array([0.44, 0.42, 0.33])

In [ ]:
pred1 >= pred2

array([ True, False,  True])

In [ ]:
np.random.seed(2)

In [ ]:
pred1 = np.random.rand(3) >= 0.3
pred1

array([ True, False,  True])

In [ ]:
pred2 = np.random.rand(3) >= 0.4
pred2

array([ True,  True, False])

### Logical operations

In [ ]:
pred1 & pred2

array([ True, False, False])

In [ ]:
pred1 | pred2

array([ True,  True,  True])

## Summarizing operations

Summarizing operations process and array and return a single number

In [ ]:
np.random.seed(2)
pred = np.random.rand(3).round(2)
pred_sum = pred.sum()
pred

array([0.44, 0.03, 0.55])

In [ ]:
pred_sum

1.02

In [ ]:
print('min = %.2f' % pred.min())
print('mean = %.2f' % pred.mean())
print('max = %.2f' % pred.max())
print('std = %.2f' % pred.std())

min = 0.03
mean = 0.34
max = 0.55
std = 0.22


For two-dimentional array it works in the same way:

In [ ]:
np.random.seed(2)
matrix = np.random.rand(4, 3).round(2)
matrix

array([[0.44, 0.03, 0.55],
       [0.44, 0.42, 0.33],
       [0.2 , 0.62, 0.3 ],
       [0.27, 0.62, 0.53]])

In [ ]:
matrix.max()

0.62

But we can specify the axis along which we apply the summarizing operation

- `axis=1` - apply to each rows
- `axis=0` - apply to each column

In [ ]:
matrix.max(axis=1)

array([0.55, 0.44, 0.62, 0.62])

In [ ]:
matrix.max(axis=0)

array([0.44, 0.62, 0.55])

In [ ]:
matrix.sum(axis=1)

array([1.02, 1.19, 1.12, 1.42])

## Sorting

In [ ]:
np.random.seed(2)
pred = np.random.rand(4).round(2)
pred

array([0.44, 0.03, 0.55, 0.44])

Creaters a new array:

In [ ]:
np.sort(pred)

array([0.03, 0.44, 0.44, 0.55])

In [ ]:
pred

array([0.44, 0.03, 0.55, 0.44])

Sorts in place:

In [ ]:
pred.sort()

In [ ]:
pred

array([0.03, 0.44, 0.44, 0.55])

Argsort - instead of sorting, return the indexes of the array in sorted order

In [ ]:
np.random.seed(2)
pred = np.random.rand(4).round(2)
pred

array([0.44, 0.03, 0.55, 0.44])

In [ ]:
idx = pred.argsort()

In [ ]:
idx

array([1, 0, 3, 2])

In [ ]:
pred[idx]

array([0.03, 0.44, 0.44, 0.55])

## Reshaping

The shape of an array cound be changed

In [ ]:
rng = np.arange(12)
rng

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [ ]:
rng.shape

(12,)

In [ ]:
rng.reshape(4, 3)

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [ ]:
rng.reshape(4, 3, order='F')

array([[ 0,  4,  8],
       [ 1,  5,  9],
       [ 2,  6, 10],
       [ 3,  7, 11]])

But number of rows x columns should be equal to the total number of elements

In [ ]:
rng.reshape(4, 4)

ValueError: cannot reshape array of size 12 into shape (4,4)

In [ ]:
vec = np.arange(3)
vec

array([0, 1, 2])

In [ ]:
mat = np.arange(6).reshape(3, 2)
mat

array([[0, 1],
       [2, 3],
       [4, 5]])

Putting mulitple arrays together:

- `concatenate`
- `hstack`
- `vstack`
- `column_stack`

In [ ]:
np.vstack([vec, vec])

array([[0, 1, 2],
       [0, 1, 2]])

In [ ]:
np.hstack([vec, vec])

array([0, 1, 2, 0, 1, 2])

In [ ]:
np.column_stack([vec, vec])

array([[0, 0],
       [1, 1],
       [2, 2]])

In [ ]:
np.concatenate([vec, vec])

array([0, 1, 2, 0, 1, 2])

In [ ]:
np.concatenate([vec, vec])

array([0, 1, 2, 0, 1, 2])

In [ ]:
np.hstack([vec, vec])

array([0, 1, 2, 0, 1, 2])

In [ ]:
np.hstack([mat, mat])

array([[0, 1, 0, 1],
       [2, 3, 2, 3],
       [4, 5, 4, 5]])

In [ ]:
np.concatenate([mat, mat])

array([[0, 1],
       [2, 3],
       [4, 5],
       [0, 1],
       [2, 3],
       [4, 5]])

In [ ]:
np.vstack([mat, mat])

array([[0, 1],
       [2, 3],
       [4, 5],
       [0, 1],
       [2, 3],
       [4, 5]])

In [ ]:
np.column_stack([vec, mat])

array([[0, 0, 1],
       [1, 2, 3],
       [2, 4, 5]])

In [ ]:
np.column_stack([vec, vec])

array([[0, 0],
       [1, 1],
       [2, 2]])

In [ ]:
np.vstack([vec, vec])

array([[0, 1, 2],
       [0, 1, 2]])

In [ ]:
np.vstack([mat, mat])

array([[0, 1],
       [2, 3],
       [4, 5],
       [0, 1],
       [2, 3],
       [4, 5]])

Transpose

In [ ]:
mat.T

array([[0, 2, 4],
       [1, 3, 5]])

In [ ]:
np.vstack([vec, mat.T])

array([[0, 1, 2],
       [0, 2, 4],
       [1, 3, 5]])

## Slicing

Taking a part of the array

In [ ]:
mat = np.arange(15).reshape(5, 3)
mat

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14]])

In [ ]:
mat[:3]

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [ ]:
mat[1:3, :2]

array([[3, 4],
       [6, 7]])

In [ ]:
mat[:, :2]

array([[ 0,  1],
       [ 3,  4],
       [ 6,  7],
       [ 9, 10],
       [12, 13]])

In [ ]:
mat[1:3, :2]

array([[3, 4],
       [6, 7]])

In [ ]:
mat[[3, 0, 1]]

array([[ 9, 10, 11],
       [ 0,  1,  2],
       [ 3,  4,  5]])

In [ ]:
mat[0,:] % 2 == 1

array([False,  True, False])

In [ ]:
mat[mat[0,:]%2 == 1]

IndexError: boolean index did not match indexed array along dimension 0; dimension is 5 but corresponding boolean dimension is 3

In [ ]:
mat[mat[:, 0] % 2 == 1]

array([[ 3,  4,  5],
       [ 9, 10, 11]])

## Linear Algebra
### Multiplication

Vector-vector multiplication

In [ ]:
u = np.array([0, 1, 2])
v = np.array([1, 2, 3])

u.dot(v)

8

Matrix-vector multiplication

In [ ]:
X = np.array([
    [0, 1, 2],
    [1, 2, 3],
    [2, 3, 3]
])

In [ ]:
u.dot(X)

array([5, 8, 9])

In [ ]:
U = np.array([
    [4, 5, 6],
    [5, 6, 7],
    [6, 7, 8]
])

In [ ]:
X.dot(U)

array([[17, 20, 23],
       [32, 38, 44],
       [41, 49, 57]])

### Inverse

To inverse a matrix, use `inv` function from `linalg` package

In [ ]:
A = np.array([
    [0, 1, 2],
    [1, 2, 3],
    [2, 3, 3]
])

In [ ]:
Ainv = np.linalg.inv(A)
Ainv

array([[-3.,  3., -1.],
       [ 3., -4.,  2.],
       [-1.,  2., -1.]])

In [ ]:
A.dot(Ainv)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

B is not invertible ("singular"):

In [ ]:
B = np.array([
    [0, 1, 1],
    [1, 2, 3],
    [2, 3, 5]
])

np.linalg.inv(B)

LinAlgError: Singular matrix

Note: When you need to solve _Ax = b_, you don't really to compute the inverse. You can use `solve`:

In [ ]:
b = np.array([1, 2, 3])

In [ ]:
x = np.linalg.solve(A, b)
x

array([0., 1., 0.])

In [ ]:
A.dot(x)

array([1., 2., 3.])